/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gordon;

/**
 *
 * @author bradlye
 */
public class qMainUI extends javax.swing.JFrame {

    /**
     * Creates new form qMainUI
     */
    public qMainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qQRCodeWindow = new javax.swing.JPanel();
        serialLabel = new javax.swing.JLabel();
        assetLabel = new javax.swing.JLabel();
        serialTextField = new javax.swing.JTextField();
        assetTextField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        dateOutLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        prevIssueScrollPane = new javax.swing.JScrollPane();
        prevIssueTextArea = new javax.swing.JTextArea();
        currentIssueScrollPane = new javax.swing.JScrollPane();
        currentIssueTextArea = new javax.swing.JTextArea();
        prevIssueLabel = new javax.swing.JLabel();
        currIssueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        qQRCodeWindow.setBackground(new java.awt.Color(240, 0, 0));

        javax.swing.GroupLayout qQRCodeWindowLayout = new javax.swing.GroupLayout(qQRCodeWindow);
        qQRCodeWindow.setLayout(qQRCodeWindowLayout);
        qQRCodeWindowLayout.setHorizontalGroup(
            qQRCodeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        qQRCodeWindowLayout.setVerticalGroup(
            qQRCodeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        serialLabel.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        serialLabel.setText("Device Name:");

        assetLabel.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        assetLabel.setText("Asset Tag:");

        serialTextField.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N

        assetTextField.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N

        dateLabel.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        dateLabel.setText("Date In:");

        dateTextField.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N

        dateOutLabel.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        dateOutLabel.setText("Date Out:");

        jTextField1.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N

        prevIssueTextArea.setColumns(20);
        prevIssueTextArea.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        prevIssueTextArea.setRows(5);
        prevIssueScrollPane.setViewportView(prevIssueTextArea);

        currentIssueTextArea.setColumns(20);
        currentIssueTextArea.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        currentIssueTextArea.setRows(5);
        currentIssueScrollPane.setViewportView(currentIssueTextArea);

        prevIssueLabel.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        prevIssueLabel.setText("Previous Issue");

        currIssueLabel.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        currIssueLabel.setText("Current Issue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(qQRCodeWindow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateOutLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(currentIssueScrollPane)
                                    .addComponent(prevIssueScrollPane))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prevIssueLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(currIssueLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(assetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(189, 189, 189)
                                            .addComponent(serialLabel))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(95, 95, 95)
                                            .addComponent(serialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(assetLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(serialLabel)
                        .addGap(18, 18, 18)
                        .addComponent(serialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(assetLabel)
                        .addGap(18, 18, 18)
                        .addComponent(assetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(qQRCodeWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prevIssueScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(prevIssueLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOutLabel))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(currentIssueScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currIssueLabel)
                        .addGap(83, 83, 83))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new qMainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assetLabel;
    private javax.swing.JTextField assetTextField;
    private javax.swing.JLabel currIssueLabel;
    private javax.swing.JScrollPane currentIssueScrollPane;
    private javax.swing.JTextArea currentIssueTextArea;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateOutLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel prevIssueLabel;
    private javax.swing.JScrollPane prevIssueScrollPane;
    private javax.swing.JTextArea prevIssueTextArea;
    private javax.swing.JPanel qQRCodeWindow;
    private javax.swing.JLabel serialLabel;
    private javax.swing.JTextField serialTextField;
    // End of variables declaration//GEN-END:variables
}
